import { applyPatch, Operation } from 'fast-json-patch';
import { DiagramType } from '../diagram/diagram.entity';

export interface PatchDriver {
  apply(baseSnapshot: string, pendingPatches: unknown[][]): string;
}

// ── JSON (Excalidraw) ─────────────────────────────────────────────────────────
// Uses RFC 6902 JSON Patch — granular ops generated by fast-json-patch on the frontend.

export class JsonPatchDriver implements PatchDriver {
  apply(baseSnapshot: string, pendingPatches: Operation[][]): string {
    if (pendingPatches.length === 0) return baseSnapshot;

    const doc     = JSON.parse(baseSnapshot || '{}');
    const flatOps = pendingPatches.flat();
    const { newDocument } = applyPatch(doc, flatOps, false, false);

    return JSON.stringify(newDocument);
  }
}

// ── XML (draw.io) ─────────────────────────────────────────────────────────────
// draw.io works on full XML — frontend sends the entire current XML as a single op.
// Each patch batch is: [{ value: "<mxGraphModel>...</mxGraphModel>" }]
// "apply" simply returns the value from the last received batch.

export interface XmlReplaceOp {
  value: string;
}

export class XmlPatchDriver implements PatchDriver {
  apply(_baseSnapshot: string, pendingPatches: XmlReplaceOp[][]): string {
    if (pendingPatches.length === 0) return _baseSnapshot;

    const lastBatch = pendingPatches[pendingPatches.length - 1];
    const lastOp    = lastBatch[lastBatch.length - 1];

    if (!lastOp?.value) {
      console.warn('[XmlPatchDriver] patch batch missing value, keeping base snapshot');
      return _baseSnapshot;
    }

    return lastOp.value;
  }
}

export function createPatchDriver(type: DiagramType): PatchDriver {
  switch (type) {
    case DiagramType.EXCALIDRAW: return new JsonPatchDriver();
    case DiagramType.DRAWIO:     return new XmlPatchDriver();
    default:
      throw new Error(`[PatchDriver] unknown diagram type: ${type}`);
  }
}